### ISSUE TITLE
Rename `*_FREQUENCY` to `*_INTERVAL`

### ISSUE THREAD

**Issue by AlexSartori** [eagletrt/canlib#6]
Tipo da

```C
#define primary_DAS_VERSION_FREQUENCY 1000
```

a

```C
#define primary_DAS_VERSION_INTERVAL 1000
```

Essendo che
> frequenza = [tempo]^(-1)
> intervallo = [tempo]

..mi sento Volpe scusate

**Comment by notfilippo** [comment]
Seems legit! Will change the config also.
